/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.model.gui;

import com.mycompany.model.PrestamoVehicular;
import com.mycompany.model.services.ServicioPrestamo;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import com.mycompany.model.TarjetaPropiedad;
import com.mycompany.model.services.ServicioTarjetaPropiedad;

/**
 *
 * @author Juan Pablo Valbuena
 */
public class GUIAddVehicular extends javax.swing.JFrame {

    /**
     * Creates new form GUIAddVehicular
     */
    public GUIAddVehicular() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdVehicular = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtTasaInteres = new javax.swing.JTextField();
        txtPlazoMeses = new javax.swing.JTextField();
        txtValorComercial = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        btnCrearPrestamoVeh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPlacaVehiculo = new javax.swing.JTextField();
        txtNumeroMotor = new javax.swing.JTextField();
        btnSeleccionarTarjeta = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI Add Prestamo Vehicular");

        jLabel1.setText("ID del Prestamo:");

        jLabel2.setText("Monto:");

        jLabel3.setText("Tasa de Interes:");

        jLabel4.setText("Plazo de Meses:");

        jLabel5.setText("Valor Comercial:");

        jLabel6.setText("Marca del Vehiculo:");

        txtIdVehicular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVehicularActionPerformed(evt);
            }
        });

        btnCrearPrestamoVeh.setText("Crear Prestamo Vehicular");
        btnCrearPrestamoVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPrestamoVehActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha de Registro:");

        jLabel8.setText("Placa Vehiculo");

        jLabel9.setText("Numero Motor");

        txtNumeroMotor.setEditable(false);

        btnSeleccionarTarjeta.setText("Seleccionar Tarjeta Propiedad");
        btnSeleccionarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnSeleccionarTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearPrestamoVeh)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtValorComercial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtIdVehicular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtMonto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTasaInteres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlazoMeses, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdVehicular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTasaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPlazoMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValorComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumeroMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearPrestamoVeh)
                    .addComponent(btnSeleccionarTarjeta))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdVehicularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVehicularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVehicularActionPerformed

    private void btnCrearPrestamoVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPrestamoVehActionPerformed

        // Valida que ya exista la tarjeta (o que esté lleno el campo)
        if (txtNumeroMotor.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Préstamo no creado. Tarjeta no encontrada. Debe buscar o crear la tarjeta de propiedad primero.");
            return;
        }

        try {
            // 1. Capturar los datos del préstamo (sin la fecha manual)
            int idPrestamo = Integer.parseInt(txtIdVehicular.getText().trim());
            double monto = Double.parseDouble(txtMonto.getText().trim());
            double tasaIntereses = Double.parseDouble(txtTasaInteres.getText().trim());
            int plazoMeses = Integer.parseInt(txtPlazoMeses.getText().trim());
            double valorComercial = Double.parseDouble(txtValorComercial.getText().trim());
            String marcaVehiculo = txtMarca.getText().trim();

            // 2. Capturar la fecha desde el JDateChooser
            java.util.Date fechaUtil = jDateChooser1.getDate();
            if (fechaUtil != null) {
                // Convertir de java.util.Date a LocalDate
                LocalDate fechaRegistro = fechaUtil.toInstant()
                        .atZone(java.time.ZoneId.systemDefault())
                        .toLocalDate();

                // 3. Buscar la tarjeta existente
                TarjetaPropiedad tarjeta = ServicioTarjetaPropiedad.getInstance().buscarTarjetaPropiedad(txtPlacaVehiculo.getText().trim());

                if (tarjeta == null) {
                    JOptionPane.showMessageDialog(this, "Tarjeta de Propiedad no encontrada. Debe crear la tarjeta primero.");
                    return;
                }

                // 4. Crear el préstamo con la tarjeta existente
                PrestamoVehicular prestamo = new PrestamoVehicular(
                        idPrestamo, monto, tasaIntereses, plazoMeses, fechaRegistro,
                        valorComercial, marcaVehiculo, tarjeta
                );

                // 5. Guardar préstamo en ServicioPrestamo
                ServicioPrestamo.getInstance().addPrestamo(prestamo);

                JOptionPane.showMessageDialog(this, "Préstamo Vehicular creado!");

                // 6. Limpiar campos
                txtIdVehicular.setText("");
                txtMonto.setText("");
                txtTasaInteres.setText("");
                txtPlazoMeses.setText("");
                txtValorComercial.setText("");
                txtMarca.setText("");
                txtPlacaVehiculo.setText("");
                txtNumeroMotor.setText("");
                jDateChooser1.setDate(null); // Limpiar el calendario

                btnCrearPrestamoVeh.setEnabled(false); // Deshabilita botón después de crear

            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear préstamo: " + e.getMessage());
        }

    }//GEN-LAST:event_btnCrearPrestamoVehActionPerformed

    private void btnSeleccionarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarTarjetaActionPerformed

        String placa = txtPlacaVehiculo.getText().trim();

        TarjetaPropiedad tarjeta = ServicioTarjetaPropiedad.getInstance().buscarTarjetaPropiedad(placa);

        if (tarjeta != null) {
            // Si existe: llena el campo del motor y habilita la creación
            txtNumeroMotor.setText(tarjeta.getNumMotor());
            JOptionPane.showMessageDialog(this, "Tarjeta encontrada!");
            btnCrearPrestamoVeh.setEnabled(true); // Habilita el botón de crear préstamo
        } else {
            // Si no existe: BLOQUEA la creación y muestra el mensaje
            txtNumeroMotor.setText("");
            JOptionPane.showMessageDialog(this, "Tarjeta no encontrada. Debe crear la Tarjeta de Propiedad en el panel de Adicionar Tarjeta de Propiedad antes de crear el Préstamo Vehicular.");
            btnCrearPrestamoVeh.setEnabled(false); // Deshabilita el botón de crear préstamo
        }
    }//GEN-LAST:event_btnSeleccionarTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAddVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAddVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAddVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAddVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAddVehicular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPrestamoVeh;
    private javax.swing.JButton btnSeleccionarTarjeta;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtIdVehicular;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumeroMotor;
    private javax.swing.JTextField txtPlacaVehiculo;
    private javax.swing.JTextField txtPlazoMeses;
    private javax.swing.JTextField txtTasaInteres;
    private javax.swing.JTextField txtValorComercial;
    // End of variables declaration//GEN-END:variables
}
