/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.model.gui;

import com.mycompany.model.Prestamo;
import com.mycompany.model.PrestamoHipotecario;
import com.mycompany.model.services.ServicioPrestamo;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pablo Valbuena
 */
public class GUIActualizarHipotecario extends javax.swing.JFrame {

    /**
     * Creates new form GUIActualizarHipotecario
     */
    public GUIActualizarHipotecario() {
        initComponents();
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdHipo = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtPlazo = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        btnActualizarHip = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI Actualizar Hipotecario");

        jLabel1.setText("ID del Prestamo:");

        jLabel2.setText("Monto:");

        jLabel3.setText("Plazo Meses:");

        jLabel4.setText("Tipo Inmueble:");

        btnActualizarHip.setText("Actualizar Prestamo Hipotecario");
        btnActualizarHip.setEnabled(false);
        btnActualizarHip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHipActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarHip))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdHipo)
                            .addComponent(txtMonto)
                            .addComponent(txtPlazo)
                            .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdHipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarHip)
                    .addComponent(btnBuscar))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (txtIdHipo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El Campo de ID del Préstamo es obligatorio");
            return;
        }
        try {
            Prestamo prestamo = ServicioPrestamo.getInstance().buscarPrestamo(Integer.parseInt(txtIdHipo.getText()));
            if (prestamo != null) {
                if (prestamo instanceof PrestamoHipotecario) {
                    PrestamoHipotecario hipo = (PrestamoHipotecario) prestamo;
                    txtMonto.setText(String.valueOf(hipo.getMonto()));
                    txtPlazo.setText(String.valueOf(hipo.getPlazoMeses()));
                    txtTipo.setText(hipo.getTipoInmueble());
                    JOptionPane.showMessageDialog(this, "Préstamo Hipotecario encontrado!");

                    // HABILITAR EL BOTÓN ACTUALIZAR
                    btnActualizarHip.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "El ID ingresado pertenece a un Préstamo Vehicular.");
                    btnActualizarHip.setEnabled(false);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Préstamo no encontrado.");
                btnActualizarHip.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
     }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarHipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHipActionPerformed
// Valida que ya se haya buscado el objeto
        if (txtMonto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Primero debe Buscar el préstamo antes de actualizar");
            return;
        }
        try {
            int id = Integer.parseInt(txtIdHipo.getText());
            double nuevoMonto = Double.parseDouble(txtMonto.getText());
            int nuevoPlazo = Integer.parseInt(txtPlazo.getText());
            String nuevoTipo = txtTipo.getText();

            boolean centinela = ServicioPrestamo.getInstance().actualizarPrestamo(
                    id, nuevoMonto, nuevoPlazo, nuevoTipo, 0 // El "0" es para el valorComercial (no aplica a hipotecario)
            );
            if (centinela) {
                // Actualizar tipo de inmueble (usando setter directo)
                PrestamoHipotecario hipo = (PrestamoHipotecario) ServicioPrestamo.getInstance().buscarPrestamo(id);
                hipo.setTipoInmueble(nuevoTipo);

                JOptionPane.showMessageDialog(this, "Préstamo Hipotecario Actualizado con Éxito");
                txtIdHipo.setText("");
                txtMonto.setText("");
                txtPlazo.setText("");
                txtTipo.setText("");

                // DESHABILITAR EL BOTÓN DESPUÉS DE ACTUALIZAR
                btnActualizarHip.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Préstamo no Encontrado/Registrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }    }//GEN-LAST:event_btnActualizarHipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIActualizarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIActualizarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIActualizarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIActualizarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIActualizarHipotecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarHip;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtIdHipo;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtPlazo;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
