/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.model.gui;

import com.mycompany.model.Prestamo;
import com.mycompany.model.PrestamoVehicular;
import com.mycompany.model.services.ServicioPrestamo;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pablo Valbuena
 */
public class GUIEliminarVehicular extends javax.swing.JFrame {

    /**
     * Creates new form GUIEliminarVehicular
     */
    public GUIEliminarVehicular() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdVehicular = new javax.swing.JTextField();
        btnEliminarVeh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtInteres = new javax.swing.JTextField();
        txtPlazo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI Eliminar Prestamo Vehicular");

        jLabel1.setText("ID del Prestamo:");

        btnEliminarVeh.setText("Eliminar Prestamo Vehicular");
        btnEliminarVeh.setEnabled(false);
        btnEliminarVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVehActionPerformed(evt);
            }
        });

        jLabel2.setText("Monto:");

        jLabel3.setText("Tasa Interes:");

        jLabel4.setText("Plazo Meses:");

        jLabel5.setText("Fecha Registro:");

        jLabel6.setText("Valor Comercial:");

        jLabel7.setText("Marca Vehiculo:");

        jLabel8.setText("Placa:");

        jLabel9.setText("NumeroMotor:");

        txtMonto.setEditable(false);

        txtInteres.setEditable(false);

        txtPlazo.setEditable(false);

        txtFecha.setEditable(false);

        txtValor.setEditable(false);

        txtMarca.setEditable(false);

        txtPlaca.setEditable(false);

        txtNumero.setEditable(false);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdVehicular, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtMonto)
                            .addComponent(txtInteres)
                            .addComponent(txtPlazo)
                            .addComponent(txtFecha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca)
                            .addComponent(txtPlaca)
                            .addComponent(txtNumero))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(27, 27, 27)
                .addComponent(btnEliminarVeh)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdVehicular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarVeh)
                    .addComponent(btnBuscar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVehActionPerformed

        // Valida que se haya buscado el préstamo antes (los campos están llenos)
        if (txtMonto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Primero debe Buscar el préstamo antes de eliminar");
            return;
        }

        try {
            int id = Integer.parseInt(txtIdVehicular.getText());

            Prestamo prestamo = ServicioPrestamo.getInstance().buscarPrestamo(id);

            if (prestamo != null) {

                if (prestamo instanceof PrestamoVehicular) {
                    PrestamoVehicular veh = (PrestamoVehicular) prestamo;

                    boolean centinela = ServicioPrestamo.getInstance().eliminarPrestamo(id);

                    if (centinela) {
                        JOptionPane.showMessageDialog(this, "Préstamo Vehicular Eliminado con Éxito");
                        txtIdVehicular.setText("");
                        // Limpiar todos los campos
                        txtMonto.setText("");
                        txtInteres.setText("");
                        txtPlazo.setText("");
                        txtFecha.setText("");
                        txtValor.setText("");
                        txtMarca.setText("");
                        txtPlaca.setText("");
                        txtNumero.setText("");

                        // DESHABILITAR EL BOTÓN DESPUÉS DE ELIMINAR
                        btnEliminarVeh.setEnabled(false);

                    } else {
                        JOptionPane.showMessageDialog(this, "Préstamo Vehicular no Encontrado/Registrado");
                        btnEliminarVeh.setEnabled(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El ID ingresado pertenece a un Préstamo Hipotecario. Vaya a la GUI de eliminar hipotecario.");
                    btnEliminarVeh.setEnabled(false);
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se Encontró ese Préstamo Vehicular");
                btnEliminarVeh.setEnabled(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            btnEliminarVeh.setEnabled(false);
        }
    }//GEN-LAST:event_btnEliminarVehActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (txtIdVehicular.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El Campo de ID del Préstamo es obligatorio");
            return;
        }

        try {
            int id = Integer.parseInt(txtIdVehicular.getText());

            Prestamo prestamo = ServicioPrestamo.getInstance().buscarPrestamo(Integer.parseInt(txtIdVehicular.getText()));

            if (prestamo != null) {

                if (prestamo instanceof PrestamoVehicular) {
                    PrestamoVehicular veh = (PrestamoVehicular) prestamo;

                    // Llenar los campos de visualización
                    txtMonto.setText(String.valueOf(veh.getMonto()));
                    txtInteres.setText(String.valueOf(veh.getTasaIntereses()));
                    txtPlazo.setText(String.valueOf(veh.getPlazoMeses()));
                    txtFecha.setText(String.valueOf(veh.getFechaRegistro()));
                    txtValor.setText(String.valueOf(veh.getValorComercial()));
                    txtMarca.setText(veh.getMarcaVehiculo());

                    // Datos de la Tarjeta de Propiedad (Asociación)
                    txtPlaca.setText(veh.getTarjetaPropiedad().getPlaca());
                    txtNumero.setText(veh.getTarjetaPropiedad().getNumMotor());

                    JOptionPane.showMessageDialog(this, "Préstamo Vehicular encontrado! \nAhora puede eliminar.");

                    // HABILITAR EL BOTÓN ELIMINAR
                    btnEliminarVeh.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "El ID ingresado pertenece a un Préstamo Hipotecario. Vaya a la GUI de eliminar hipotecario.");
                    btnEliminarVeh.setEnabled(false);
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se Encontró ese Préstamo Vehicular");
                btnEliminarVeh.setEnabled(false);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
            btnEliminarVeh.setEnabled(false);

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEliminarVehicular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarVeh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdVehicular;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPlazo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
