/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.model.gui;

import com.mycompany.model.Prestamo;
import com.mycompany.model.PrestamoVehicular;
import com.mycompany.model.TarjetaPropiedad;
import com.mycompany.model.services.ServicioPrestamo;
import com.mycompany.model.services.ServicioTarjetaPropiedad;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pablo Valbuena
 */
public class GUIEliminarTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form GUIEliminarTarjeta
     */
    public GUIEliminarTarjeta() {
        initComponents();
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtNumMotor = new javax.swing.JTextField();
        btnBuscarTarjeta = new javax.swing.JButton();
        btnEliminarTarjeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI Eliminar Tarjeta");

        jLabel1.setText("Placa:");

        jLabel2.setText("NumMotor:");

        txtNumMotor.setEditable(false);

        btnBuscarTarjeta.setText("Buscar");
        btnBuscarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTarjetaActionPerformed(evt);
            }
        });

        btnEliminarTarjeta.setText("Eliminar Tarjeta de Propiedad");
        btnEliminarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtNumMotor)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarTarjeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnEliminarTarjeta)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarTarjeta)
                    .addComponent(btnBuscarTarjeta))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTarjetaActionPerformed

        if (txtPlaca.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El Campo de Placa es obligatorio");
            return;
        }

        try {
            TarjetaPropiedad tarjeta = ServicioTarjetaPropiedad.getInstance().buscarTarjetaPropiedad(txtPlaca.getText().trim());

            if (tarjeta != null) {
                // Llenar el campo de numero de motor
                txtNumMotor.setText(tarjeta.getNumMotor());

                JOptionPane.showMessageDialog(this, "Tarjeta de Propiedad encontrada! \nAhora puede eliminar.");
            } else {
                JOptionPane.showMessageDialog(this, "Tarjeta de Propiedad no Encontrada/Registrada");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarTarjetaActionPerformed

    private void btnEliminarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTarjetaActionPerformed
        // Verificar si ya se buscó la tarjeta (el campo de NumMotor está lleno)
        if (txtNumMotor.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Primero debe Buscar la tarjeta antes de eliminar");
            return;
        }

        try {
            // 1. Extraer la placa
            String placa = txtPlaca.getText().trim();

            // 2. Verificar si hay préstamo vehicular asociado
            boolean hayPrestamoAsociado = false;
            Map<Integer, Prestamo> prestamos = ServicioPrestamo.getInstance().getPrestamos();
            for (Prestamo prestamo : prestamos.values()) {
                if (prestamo instanceof PrestamoVehicular) {
                    PrestamoVehicular veh = (PrestamoVehicular) prestamo;
                    if (veh.getTarjetaPropiedad().getPlaca().equals(placa)) {
                        hayPrestamoAsociado = true;
                        break;
                    }
                }
            }

            // 3. Si hay préstamo asociado, no permitir la eliminación
            if (hayPrestamoAsociado) {
                JOptionPane.showMessageDialog(this, "Esta tarjeta está asociada a un Préstamo Vehicular. \nNo se puede eliminar.");
                return;
            }

            // 4. Eliminar (si no hay préstamo asociado)
            boolean centinela = ServicioTarjetaPropiedad.getInstance().eliminarTarjetaPropiedad(placa);

            if (centinela) {
                JOptionPane.showMessageDialog(this, "Tarjeta de Propiedad Eliminada con Éxito");
                // Limpiar todos los campos
                txtPlaca.setText("");
                txtNumMotor.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Tarjeta de Propiedad no Encontrada/Registrada");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEliminarTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTarjeta;
    private javax.swing.JButton btnEliminarTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNumMotor;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
