/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.model.gui;

import com.mycompany.model.Prestamo;
import com.mycompany.model.PrestamoHipotecario;
import com.mycompany.model.services.ServicioPrestamo;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pablo Valbuena
 */
public class GUIEliminarHipotecario extends javax.swing.JFrame {

    /**
     * Creates new form GUIEliminarHipotecario
     */
    public GUIEliminarHipotecario() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdPrestamoHipotecario = new javax.swing.JTextField();
        btnEliminarHipotecario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI Eliminar Prestamo Hipotecario");

        jLabel1.setText("ID del Prestamo:");

        btnEliminarHipotecario.setText("Eliminar Prestamo Hipotecario");
        btnEliminarHipotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHipotecarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarHipotecario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtIdPrestamoHipotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdPrestamoHipotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarHipotecario)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarHipotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHipotecarioActionPerformed

        if (txtIdPrestamoHipotecario.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El Campo de ID del Préstamo es obligatorio");
            return;
        }

        try {
            int id = Integer.parseInt(txtIdPrestamoHipotecario.getText());
            Prestamo prestamo = ServicioPrestamo.buscarPrestamo(id);

            if (prestamo != null) {

                if (prestamo instanceof PrestamoHipotecario) {

                    PrestamoHipotecario hipo = (PrestamoHipotecario) prestamo;

                    boolean centinela = ServicioPrestamo.eliminarPrestamo(id);

                    if (centinela) {
                        JOptionPane.showMessageDialog(this, "Préstamo Hipotecario Eliminado con Éxito");
                        txtIdPrestamoHipotecario.setText(""); 
                    } else {
                        JOptionPane.showMessageDialog(this, "Préstamo Hipotecario no Encontrado/Registrado");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "El ID ingresado pertenece a un Préstamo Vehicular. Vaya a la GUI de eliminar vehicular.");
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se Encontró ese Préstamo Hipotecario");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarHipotecarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEliminarHipotecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarHipotecario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtIdPrestamoHipotecario;
    // End of variables declaration//GEN-END:variables
}
