/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.model.gui;

import com.mycompany.model.ICambiable;
import com.mycompany.model.Prestamo;
import com.mycompany.model.PrestamoHipotecario;
import com.mycompany.model.services.ServicioPrestamo;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Pablo Valbuena
 */
public class GUIListarHipotecario extends javax.swing.JFrame implements ICambiable {

    /**
     * Creates new form GUIListarHipotecario
     */
    public GUIListarHipotecario() {
        initComponents();
        setLocationRelativeTo(this);
        ServicioPrestamo.getInstance().addGUI(this); // Suscribirse al Observer

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarHipotecario = new javax.swing.JTable();
        btnListarHipotecario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI Listar Prestamo Hipotecario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tblListarHipotecario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Prestamo", "Monto", "Tasa Interes", "Plazo Meses", "Fecha Regsitro", "Tipo Inmueble", "Direccion Inmueble"
            }
        ));
        jScrollPane1.setViewportView(tblListarHipotecario);

        btnListarHipotecario.setText("Listar Prestamo Hipotecario");
        btnListarHipotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarHipotecarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListarHipotecario)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListarHipotecario)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarHipotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarHipotecarioActionPerformed

        Map<Integer, Prestamo> prestamos = ServicioPrestamo.getInstance().getPrestamos();

        DefaultTableModel modelo = (DefaultTableModel) tblListarHipotecario.getModel();
        modelo.setRowCount(0);

        for (Prestamo prestamo : prestamos.values()) {

            if (prestamo instanceof PrestamoHipotecario) {

                PrestamoHipotecario hipo = (PrestamoHipotecario) prestamo;

                Object[] fila = new Object[]{
                    hipo.getIdPrestamo(),
                    String.format("$ %, .0f", hipo.getMonto()),
                    hipo.getTasaIntereses(),
                    hipo.getPlazoMeses(),
                    hipo.getFechaRegistro(),
                    hipo.getTipoInmueble(),
                    hipo.getDireccionInmueble()
                };
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_btnListarHipotecarioActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ServicioPrestamo.getInstance().delGUI(this); // Desuscribirse del Observer
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIListarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIListarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIListarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIListarHipotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIListarHipotecario().setVisible(true);
            }
        });
    }

    @Override
    public void cambio() {
        // 1. Obtener la lista de préstamos
        Map<Integer, Prestamo> prestamos = ServicioPrestamo.getInstance().getPrestamos();

        // 2. Llenar la tabla (la misma lógica que el botón "Listar")
        DefaultTableModel modelo = (DefaultTableModel) tblListarHipotecario.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Prestamo prestamo : prestamos.values()) {
            if (prestamo instanceof PrestamoHipotecario) {
                PrestamoHipotecario hipo = (PrestamoHipotecario) prestamo;
                Object[] fila = new Object[]{
                    hipo.getIdPrestamo(),
                    hipo.getMonto(),
                    hipo.getTasaIntereses(),
                    hipo.getPlazoMeses(),
                    hipo.getFechaRegistro(),
                    hipo.getTipoInmueble(),
                    hipo.getDireccionInmueble()
                };
                modelo.addRow(fila);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarHipotecario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListarHipotecario;
    // End of variables declaration//GEN-END:variables
}
