/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.model.gui;

import com.mycompany.model.ICambiable;
import com.mycompany.model.Prestamo;
import com.mycompany.model.PrestamoVehicular;
import com.mycompany.model.services.ServicioPrestamo;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Pablo Valbuena
 */
public class GUIListarVehicular extends javax.swing.JFrame implements ICambiable {

    /**
     * Creates new form GUIListarVehicular
     */
    public GUIListarVehicular() {
        initComponents();
        setLocationRelativeTo(this);
        ServicioPrestamo.getInstance().addGUI(this); // Suscribirse al Observer

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarVehicular = new javax.swing.JTable();
        txtListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI Listar Prestamo Vehicular");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tblListarVehicular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Prestamo", "Monto", "Tasa Interes", "Plazo Meses", "Fecha Registro", "Valor Comercial", "Marca Vehiculo", "Placa Vehiculo", "NumMotor"
            }
        ));
        jScrollPane1.setViewportView(tblListarVehicular);

        txtListar.setText("Listar Prestamos Vehicular");
        txtListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtListar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(txtListar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtListarActionPerformed

        Map<Integer, Prestamo> prestamos = ServicioPrestamo.getInstance().getPrestamos();

        DefaultTableModel modelo = (DefaultTableModel) tblListarVehicular.getModel();
        modelo.setRowCount(0);

        for (Prestamo prestamo : prestamos.values()) {

            if (prestamo instanceof PrestamoVehicular) {

                PrestamoVehicular veh = (PrestamoVehicular) prestamo;

                Object[] fila = new Object[]{
                    veh.getIdPrestamo(),
                    String.format("$ %, .0f", veh.getMonto()),
                    veh.getTasaIntereses(),
                    veh.getPlazoMeses(),
                    veh.getFechaRegistro(),
                    String.format("$ %, .0f", veh.getValorComercial()),
                    veh.getMarcaVehiculo(),
                    veh.getTarjetaPropiedad().getPlaca(),
                    veh.getTarjetaPropiedad().getNumMotor()

                };
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_txtListarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ServicioPrestamo.getInstance().delGUI(this); // Desuscribirse del Observer
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIListarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIListarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIListarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIListarVehicular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIListarVehicular().setVisible(true);
            }
        });
    }

    @Override
    public void cambio() {
        // 1. Obtener la lista de préstamos
        Map<Integer, Prestamo> prestamos = ServicioPrestamo.getInstance().getPrestamos();

        // 2. Llenar la tabla (la misma lógica que el botón "Listar")
        DefaultTableModel modelo = (DefaultTableModel) tblListarVehicular.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Prestamo prestamo : prestamos.values()) {
            if (prestamo instanceof PrestamoVehicular) {
                PrestamoVehicular veh = (PrestamoVehicular) prestamo;
                Object[] fila = new Object[]{
                    veh.getIdPrestamo(),
                    veh.getMonto(),
                    veh.getTasaIntereses(),
                    veh.getPlazoMeses(),
                    veh.getFechaRegistro(),
                    veh.getValorComercial(),
                    veh.getMarcaVehiculo(),
                    veh.getTarjetaPropiedad().getPlaca(),
                    veh.getTarjetaPropiedad().getNumMotor()
                        
                };
                modelo.addRow(fila);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListarVehicular;
    private javax.swing.JButton txtListar;
    // End of variables declaration//GEN-END:variables
}
